#!/usr/bin/with-contenv bash

echo "# plex_autoscan waiting for Plex service"
s6-svwait ../plex && sleep 1

echo "# plex_autoscan starting..."
exec s6-setuidgid plex /bin/bash -c 'python3.5 /plex_autoscan/scan.py server'
