#!/usr/bin/with-contenv bash

# If the first run completed successfully, we are done
if [ -e /.firstPlexdriveRunComplete ]; then
  exit 0
fi
mkdir -p /config/.config/${PLEXDRIVE_CONFIG_DIR}
configSubDir="/config/.config/${PLEXDRIVE_CONFIG_DIR}"

# Update ownership of dirs we need to write
chown -Rc root:root ${configSubDir}

mkdir -p ${PLEXDRIVE_MOUNT_POINT} 2>/dev/null
chown -Rc root:root ${PLEXDRIVE_MOUNT_POINT}

touch /.firstPlexdriveRunComplete
